// Code generated by protoc-gen-go.
// source: server_protocol.proto
// DO NOT EDIT!

/*
Package MysticSalesmanServerProtocol is a generated protocol buffer package.

It is generated from these files:
	server_protocol.proto

It has these top-level messages:
	QueryUserGroup
	QueryUserGroupReply
*/
package MysticSalesmanServerProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type QueryUserGroup struct {
	Uin              *uint32 `protobuf:"varint,1,opt,name=uin" json:"uin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryUserGroup) Reset()                    { *m = QueryUserGroup{} }
func (m *QueryUserGroup) String() string            { return proto.CompactTextString(m) }
func (*QueryUserGroup) ProtoMessage()               {}
func (*QueryUserGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryUserGroup) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

type QueryUserGroupReply struct {
	Uin              *uint32 `protobuf:"varint,1,opt,name=uin" json:"uin,omitempty"`
	UserGroup        *uint32 `protobuf:"varint,2,opt,name=user_group" json:"user_group,omitempty"`
	SalesFrom        *uint32 `protobuf:"varint,3,opt,name=sales_from" json:"sales_from,omitempty"`
	SalesTo          *uint32 `protobuf:"varint,4,opt,name=sales_to" json:"sales_to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryUserGroupReply) Reset()                    { *m = QueryUserGroupReply{} }
func (m *QueryUserGroupReply) String() string            { return proto.CompactTextString(m) }
func (*QueryUserGroupReply) ProtoMessage()               {}
func (*QueryUserGroupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryUserGroupReply) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *QueryUserGroupReply) GetUserGroup() uint32 {
	if m != nil && m.UserGroup != nil {
		return *m.UserGroup
	}
	return 0
}

func (m *QueryUserGroupReply) GetSalesFrom() uint32 {
	if m != nil && m.SalesFrom != nil {
		return *m.SalesFrom
	}
	return 0
}

func (m *QueryUserGroupReply) GetSalesTo() uint32 {
	if m != nil && m.SalesTo != nil {
		return *m.SalesTo
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryUserGroup)(nil), "MysticSalesmanServerProtocol.QueryUserGroup")
	proto.RegisterType((*QueryUserGroupReply)(nil), "MysticSalesmanServerProtocol.QueryUserGroupReply")
}

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x64,
	0x7c, 0x2b, 0x8b, 0x4b, 0x32, 0x93, 0x83, 0x13, 0x73, 0x52, 0x8b, 0x73, 0x13, 0xf3, 0x82, 0xc1,
	0x8a, 0x02, 0xa0, 0x6a, 0x94, 0x64, 0xb9, 0xf8, 0x02, 0x4b, 0x53, 0x8b, 0x2a, 0x43, 0x81, 0x9a,
	0xdd, 0x8b, 0xf2, 0x4b, 0x0b, 0x84, 0xb8, 0xb9, 0x98, 0x4b, 0x33, 0xf3, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x95, 0x62, 0xb8, 0x84, 0x51, 0xa5, 0x83, 0x52, 0x0b, 0x72, 0x2a, 0x51, 0xd4, 0x08,
	0x09, 0x71, 0x71, 0x95, 0x02, 0xa5, 0xe3, 0xd3, 0x41, 0xf2, 0x12, 0x4c, 0x30, 0xb1, 0x62, 0x90,
	0x85, 0xf1, 0x69, 0x45, 0xf9, 0xb9, 0x12, 0xcc, 0x60, 0x31, 0x01, 0x2e, 0x0e, 0x88, 0x58, 0x49,
	0xbe, 0x04, 0x0b, 0x48, 0x04, 0x10, 0x00, 0x00, 0xff, 0xff, 0x21, 0xca, 0x13, 0x5e, 0xb2, 0x00,
	0x00, 0x00,
}
