// Code generated by protoc-gen-go.
// source: server_protocol.proto
// DO NOT EDIT!

/*
Package stateserverprotocol is a generated protocol buffer package.

It is generated from these files:
	server_protocol.proto

It has these top-level messages:
	Message
	UpdateStateRequest
	PickRandomFactionRequest
	PickRandomFactionResponse
*/
package stateserverprotocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageCommand int32

const (
	MessageCommand_UpdateStateRequestCmd        MessageCommand = 1000
	MessageCommand_PickRandomFactionRequestCmd  MessageCommand = 1100
	MessageCommand_PickRandomFactionResponseCmd MessageCommand = 1101
)

var MessageCommand_name = map[int32]string{
	1000: "UpdateStateRequestCmd",
	1100: "PickRandomFactionRequestCmd",
	1101: "PickRandomFactionResponseCmd",
}
var MessageCommand_value = map[string]int32{
	"UpdateStateRequestCmd":        1000,
	"PickRandomFactionRequestCmd":  1100,
	"PickRandomFactionResponseCmd": 1101,
}

func (x MessageCommand) Enum() *MessageCommand {
	p := new(MessageCommand)
	*p = x
	return p
}
func (x MessageCommand) String() string {
	return proto.EnumName(MessageCommand_name, int32(x))
}
func (x *MessageCommand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageCommand_value, data, "MessageCommand")
	if err != nil {
		return err
	}
	*x = MessageCommand(value)
	return nil
}
func (MessageCommand) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Cmd              *uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Ctx              *uint32 `protobuf:"varint,2,opt,name=ctx" json:"ctx,omitempty"`
	Payload          []byte  `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Message) GetCtx() uint32 {
	if m != nil && m.Ctx != nil {
		return *m.Ctx
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateStateRequest struct {
	GroupIndex       *uint32 `protobuf:"varint,1,opt,name=group_index" json:"group_index,omitempty"`
	FactionId        *uint32 `protobuf:"varint,2,opt,name=faction_id" json:"faction_id,omitempty"`
	UnderProtection  *bool   `protobuf:"varint,3,opt,name=under_protection" json:"under_protection,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateStateRequest) Reset()                    { *m = UpdateStateRequest{} }
func (m *UpdateStateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateStateRequest) ProtoMessage()               {}
func (*UpdateStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateStateRequest) GetGroupIndex() uint32 {
	if m != nil && m.GroupIndex != nil {
		return *m.GroupIndex
	}
	return 0
}

func (m *UpdateStateRequest) GetFactionId() uint32 {
	if m != nil && m.FactionId != nil {
		return *m.FactionId
	}
	return 0
}

func (m *UpdateStateRequest) GetUnderProtection() bool {
	if m != nil && m.UnderProtection != nil {
		return *m.UnderProtection
	}
	return false
}

type PickRandomFactionRequest struct {
	GroupIndex       *uint32 `protobuf:"varint,1,opt,name=group_index" json:"group_index,omitempty"`
	SelfFactionId    *uint32 `protobuf:"varint,2,opt,name=self_faction_id" json:"self_faction_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PickRandomFactionRequest) Reset()                    { *m = PickRandomFactionRequest{} }
func (m *PickRandomFactionRequest) String() string            { return proto.CompactTextString(m) }
func (*PickRandomFactionRequest) ProtoMessage()               {}
func (*PickRandomFactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PickRandomFactionRequest) GetGroupIndex() uint32 {
	if m != nil && m.GroupIndex != nil {
		return *m.GroupIndex
	}
	return 0
}

func (m *PickRandomFactionRequest) GetSelfFactionId() uint32 {
	if m != nil && m.SelfFactionId != nil {
		return *m.SelfFactionId
	}
	return 0
}

type PickRandomFactionResponse struct {
	FactionId        *uint32 `protobuf:"varint,1,opt,name=faction_id" json:"faction_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PickRandomFactionResponse) Reset()                    { *m = PickRandomFactionResponse{} }
func (m *PickRandomFactionResponse) String() string            { return proto.CompactTextString(m) }
func (*PickRandomFactionResponse) ProtoMessage()               {}
func (*PickRandomFactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PickRandomFactionResponse) GetFactionId() uint32 {
	if m != nil && m.FactionId != nil {
		return *m.FactionId
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "stateserverprotocol.Message")
	proto.RegisterType((*UpdateStateRequest)(nil), "stateserverprotocol.UpdateStateRequest")
	proto.RegisterType((*PickRandomFactionRequest)(nil), "stateserverprotocol.PickRandomFactionRequest")
	proto.RegisterType((*PickRandomFactionResponse)(nil), "stateserverprotocol.PickRandomFactionResponse")
	proto.RegisterEnum("stateserverprotocol.MessageCommand", MessageCommand_name, MessageCommand_value)
}

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x55, 0xba, 0x48, 0x34, 0x05, 0x5a, 0xb9, 0xaa, 0x30, 0x3f, 0x8b, 0x92, 0x15, 0x62,
	0x01, 0x1b, 0x6e, 0x50, 0x09, 0xb1, 0x41, 0x42, 0x45, 0x88, 0x65, 0x64, 0xc5, 0xd3, 0x2a, 0x22,
	0xce, 0xb8, 0x19, 0x07, 0x95, 0x3b, 0xc2, 0x3d, 0x38, 0x06, 0x8e, 0x13, 0x36, 0x85, 0x74, 0xe7,
	0xf1, 0x7b, 0xef, 0xf3, 0xf3, 0xc0, 0x8c, 0xb1, 0x7a, 0xc7, 0x2a, 0xb5, 0x15, 0x39, 0xca, 0xa8,
	0xb8, 0x09, 0x07, 0x31, 0x65, 0xa7, 0x1c, 0xb6, 0xda, 0xaf, 0x94, 0xdc, 0x41, 0xf4, 0x88, 0xcc,
	0x6a, 0x8d, 0x62, 0x04, 0xc3, 0xcc, 0x68, 0x39, 0x98, 0x0f, 0xae, 0x8e, 0xc2, 0xe0, 0xb6, 0xf2,
	0x20, 0x0c, 0x63, 0x88, 0xac, 0xfa, 0x28, 0x48, 0x69, 0x39, 0xf4, 0x17, 0x87, 0xc9, 0x2b, 0x88,
	0x17, 0xab, 0x3d, 0xed, 0xb9, 0x41, 0x2e, 0x71, 0x53, 0x23, 0x3b, 0x31, 0x85, 0xd1, 0xba, 0xa2,
	0xda, 0xa6, 0x79, 0xa9, 0x71, 0xdb, 0x81, 0x04, 0xc0, 0x4a, 0x65, 0x2e, 0xa7, 0x32, 0xcd, 0x75,
	0xc7, 0x93, 0x30, 0xa9, 0xbd, 0xa5, 0x6d, 0x88, 0x41, 0x0c, 0xe0, 0x38, 0x79, 0x00, 0xf9, 0x94,
	0x67, 0x6f, 0x4b, 0x55, 0x6a, 0x32, 0xf7, 0x6d, 0x6e, 0x2f, 0xfe, 0x04, 0xc6, 0x8c, 0xc5, 0x2a,
	0xdd, 0x7d, 0x23, 0xb9, 0x85, 0xd3, 0x7f, 0x48, 0x6c, 0xa9, 0x64, 0xdc, 0x29, 0x15, 0x48, 0xd7,
	0x1b, 0x38, 0xee, 0x36, 0xb1, 0x20, 0x63, 0x7c, 0x4c, 0x9c, 0xc1, 0xec, 0xef, 0x2f, 0x17, 0x46,
	0x4f, 0xbe, 0x23, 0x31, 0x87, 0xf3, 0xbe, 0xa2, 0x8d, 0xe3, 0x33, 0x16, 0x97, 0x70, 0xd1, 0x5b,
	0xa0, 0xb1, 0x7c, 0xc5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0xaa, 0x8c, 0xa9, 0xa9, 0x01,
	0x00, 0x00,
}
