// Code generated by protoc-gen-go.
// source: server_protocol.proto
// DO NOT EDIT!

/*
Package regionserverprotocol is a generated protocol buffer package.

It is generated from these files:
	server_protocol.proto

It has these top-level messages:
	Message
	UpdateRegionRequest
	PickFromRegionRequest
	PickFromRegionResponse
	RegionStatus
	RegionStatusRequest
	RegionStatusResponse
*/
package regionserverprotocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageCommand int32

const (
	MessageCommand_UpdateRegionRequestCmd    MessageCommand = 1000
	MessageCommand_PickFromRegionRequestCmd  MessageCommand = 1010
	MessageCommand_PickFromRegionResponseCmd MessageCommand = 1011
	MessageCommand_RegionStatusRequestCmd    MessageCommand = 1020
	MessageCommand_RegionStatusResponseCmd   MessageCommand = 1021
)

var MessageCommand_name = map[int32]string{
	1000: "UpdateRegionRequestCmd",
	1010: "PickFromRegionRequestCmd",
	1011: "PickFromRegionResponseCmd",
	1020: "RegionStatusRequestCmd",
	1021: "RegionStatusResponseCmd",
}
var MessageCommand_value = map[string]int32{
	"UpdateRegionRequestCmd":    1000,
	"PickFromRegionRequestCmd":  1010,
	"PickFromRegionResponseCmd": 1011,
	"RegionStatusRequestCmd":    1020,
	"RegionStatusResponseCmd":   1021,
}

func (x MessageCommand) Enum() *MessageCommand {
	p := new(MessageCommand)
	*p = x
	return p
}
func (x MessageCommand) String() string {
	return proto.EnumName(MessageCommand_name, int32(x))
}
func (x *MessageCommand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageCommand_value, data, "MessageCommand")
	if err != nil {
		return err
	}
	*x = MessageCommand(value)
	return nil
}
func (MessageCommand) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Cmd              *uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Ctx              *uint32 `protobuf:"varint,2,opt,name=ctx" json:"ctx,omitempty"`
	Payload          []byte  `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Message) GetCtx() uint32 {
	if m != nil && m.Ctx != nil {
		return *m.Ctx
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateRegionRequest struct {
	Uin              *uint32 `protobuf:"varint,1,opt,name=uin" json:"uin,omitempty"`
	Level            *uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Region           *uint32 `protobuf:"varint,3,opt,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRegionRequest) Reset()                    { *m = UpdateRegionRequest{} }
func (m *UpdateRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRegionRequest) ProtoMessage()               {}
func (*UpdateRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateRegionRequest) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *UpdateRegionRequest) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *UpdateRegionRequest) GetRegion() uint32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

type PickFromRegionRequest struct {
	SelfUin          *uint32 `protobuf:"varint,1,opt,name=self_uin" json:"self_uin,omitempty"`
	SelfLevel        *uint32 `protobuf:"varint,2,opt,name=self_level" json:"self_level,omitempty"`
	ExpectRegion     *uint32 `protobuf:"varint,3,opt,name=expect_region" json:"expect_region,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PickFromRegionRequest) Reset()                    { *m = PickFromRegionRequest{} }
func (m *PickFromRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*PickFromRegionRequest) ProtoMessage()               {}
func (*PickFromRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PickFromRegionRequest) GetSelfUin() uint32 {
	if m != nil && m.SelfUin != nil {
		return *m.SelfUin
	}
	return 0
}

func (m *PickFromRegionRequest) GetSelfLevel() uint32 {
	if m != nil && m.SelfLevel != nil {
		return *m.SelfLevel
	}
	return 0
}

func (m *PickFromRegionRequest) GetExpectRegion() uint32 {
	if m != nil && m.ExpectRegion != nil {
		return *m.ExpectRegion
	}
	return 0
}

type PickFromRegionResponse struct {
	Uin              []uint32 `protobuf:"varint,1,rep,name=uin" json:"uin,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PickFromRegionResponse) Reset()                    { *m = PickFromRegionResponse{} }
func (m *PickFromRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*PickFromRegionResponse) ProtoMessage()               {}
func (*PickFromRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PickFromRegionResponse) GetUin() []uint32 {
	if m != nil {
		return m.Uin
	}
	return nil
}

type RegionStatus struct {
	Region           *uint32 `protobuf:"varint,1,opt,name=region" json:"region,omitempty"`
	Num              *uint32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegionStatus) Reset()                    { *m = RegionStatus{} }
func (m *RegionStatus) String() string            { return proto.CompactTextString(m) }
func (*RegionStatus) ProtoMessage()               {}
func (*RegionStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegionStatus) GetRegion() uint32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

func (m *RegionStatus) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type RegionStatusRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegionStatusRequest) Reset()                    { *m = RegionStatusRequest{} }
func (m *RegionStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionStatusRequest) ProtoMessage()               {}
func (*RegionStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RegionStatusResponse struct {
	Status           []*RegionStatus `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RegionStatusResponse) Reset()                    { *m = RegionStatusResponse{} }
func (m *RegionStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionStatusResponse) ProtoMessage()               {}
func (*RegionStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RegionStatusResponse) GetStatus() []*RegionStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "regionserverprotocol.Message")
	proto.RegisterType((*UpdateRegionRequest)(nil), "regionserverprotocol.UpdateRegionRequest")
	proto.RegisterType((*PickFromRegionRequest)(nil), "regionserverprotocol.PickFromRegionRequest")
	proto.RegisterType((*PickFromRegionResponse)(nil), "regionserverprotocol.PickFromRegionResponse")
	proto.RegisterType((*RegionStatus)(nil), "regionserverprotocol.RegionStatus")
	proto.RegisterType((*RegionStatusRequest)(nil), "regionserverprotocol.RegionStatusRequest")
	proto.RegisterType((*RegionStatusResponse)(nil), "regionserverprotocol.RegionStatusResponse")
	proto.RegisterEnum("regionserverprotocol.MessageCommand", MessageCommand_name, MessageCommand_value)
}

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x99, 0xc3, 0x45, 0xee, 0xd6, 0x39, 0xb2, 0x75, 0x56, 0xfc, 0x83, 0x04, 0x04, 0x51,
	0xd8, 0xc3, 0xf0, 0x0b, 0xc8, 0xc0, 0x07, 0x41, 0x90, 0xa9, 0xcf, 0x23, 0xb4, 0xd7, 0x31, 0x6c,
	0x9a, 0xda, 0xa4, 0x63, 0x7e, 0x22, 0xbf, 0x9a, 0xcf, 0xfa, 0xaa, 0xe0, 0x92, 0x56, 0xd7, 0x4a,
	0xde, 0x9a, 0x7b, 0x92, 0xdf, 0x3d, 0xe7, 0x14, 0x7c, 0x85, 0xd9, 0x12, 0xb3, 0x59, 0x9a, 0x49,
	0x2d, 0x43, 0x19, 0x8f, 0xec, 0x07, 0x1d, 0x64, 0x38, 0x5f, 0xc8, 0xa4, 0x10, 0x7f, 0x35, 0x76,
	0x09, 0xe4, 0x16, 0x95, 0xe2, 0x73, 0xa4, 0x6d, 0x68, 0x86, 0x22, 0x0a, 0x1a, 0x27, 0x8d, 0x33,
	0xcf, 0x1e, 0xf4, 0x2a, 0xd8, 0xb2, 0x87, 0x5d, 0x20, 0x29, 0x7f, 0x8d, 0x25, 0x8f, 0x82, 0xe6,
	0x7a, 0xd0, 0x61, 0x57, 0xd0, 0x7f, 0x4c, 0x23, 0xae, 0x71, 0x6a, 0x99, 0x53, 0x7c, 0xc9, 0x51,
	0x69, 0xf3, 0x28, 0x5f, 0x24, 0x25, 0xc1, 0x83, 0xed, 0x18, 0x97, 0x18, 0x97, 0x8c, 0x2e, 0xb4,
	0x0a, 0x03, 0x16, 0xe1, 0xb1, 0x07, 0xf0, 0xef, 0x16, 0xe1, 0xf3, 0x75, 0x26, 0x45, 0x1d, 0xd2,
	0x83, 0x1d, 0x85, 0xf1, 0xd3, 0x6c, 0x43, 0xa2, 0x00, 0x76, 0x52, 0xc5, 0xf9, 0xe0, 0xe1, 0x2a,
	0xc5, 0x50, 0xcf, 0x6a, 0xd4, 0x53, 0x18, 0xfe, 0xa7, 0xaa, 0xd4, 0x84, 0xde, 0x78, 0x6b, 0xae,
	0xaf, 0x5d, 0x40, 0xa7, 0x90, 0xef, 0x35, 0xd7, 0xb9, 0xaa, 0x98, 0xfb, 0x4b, 0x9f, 0xe4, 0xa2,
	0x58, 0xc5, 0x7c, 0xe8, 0x57, 0x2f, 0x97, 0x3e, 0xd9, 0x0d, 0x0c, 0xea, 0xe3, 0x72, 0xd1, 0x18,
	0x5a, 0xca, 0x4e, 0xec, 0xae, 0xf6, 0x98, 0x8d, 0x5c, 0xc5, 0x8f, 0xaa, 0x6f, 0xcf, 0xdf, 0x1a,
	0xd0, 0x2d, 0x7f, 0xc3, 0x44, 0x0a, 0xc1, 0x93, 0x88, 0x1e, 0xc0, 0xd0, 0x51, 0xf1, 0x44, 0x44,
	0xbd, 0x77, 0x42, 0x8f, 0x20, 0x70, 0x96, 0x67, 0xe4, 0x0f, 0x42, 0x8f, 0x61, 0xdf, 0xdd, 0x82,
	0xd1, 0x3f, 0x89, 0x61, 0x3b, 0x12, 0x19, 0xf1, 0x8b, 0xd0, 0x43, 0xd8, 0x73, 0xe5, 0x32, 0xea,
	0x37, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xec, 0xcd, 0xf7, 0xf9, 0x5d, 0x02, 0x00, 0x00,
}
